
server:
    port: 8081
spring:
    cloud:
        config:
            server:
                git:
                    default-label: main
                    uri: https://github.com/eltiolopez/tutorial-microservices
                    seach-paths: config-data
    application:
        name: config-service