server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          # Git repo branch name:
          default-label: config-server
          # Git repo uri:
          uri: https://github.com/eltiolopez/tutorial-microservices
          # Git repo config dir:
          search-paths: config-data
  application:
    name: config-service
